export const HOME = '/'
export const BROWSE = '/gallery'
export const ROOM = '/room:roomurl'
export const ABOUT = '/about-us'
export const POST_ID = '/posts/:id'
export const POSTS_FORM = '/posts/new'