/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import React, { useRef, useEffect } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
export default function Model(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/kick.glb");
  const { actions } = useAnimations(animations, group);

  useEffect(() => {
    console.log(actions);
    actions.Kick.play();
  });

  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]} scale={[0.01, 0.01, 0.01]}>
        <primitive object={nodes.mixamorigHips} />
        <skinnedMesh
          geometry={nodes.Ch03.geometry}
          material={materials.Ch03_Body}
          skeleton={nodes.Ch03.skeleton}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/kick.glb");
